{% set version="3.22.0" %}
{% set ver = version.replace(".", "") + "000" %}

package:
  name: sqlite
  version: {{ version }}

source:
  url: https://www.sqlite.org/2018/sqlite-autoconf-{{ ver }}.tar.gz
  sha256: 2824ab1238b706bc66127320afbdffb096361130e23291f26928a027b885c612
  patches:
    - expose_symbols.patch  # [win]

build:
  number: 1
  run_exports:
    # sometimes adds new symbols.  Default behavior is OK.
    #    https://abi-laboratory.pro/tracker/timeline/sqlite/
    - {{ pin_subpackage('sqlite') }}

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config    # [not win]
  host:
    - ncurses       # [unix]
    - readline      # [unix and GPL_ok==1]

test:
  commands:
    - sqlite3 --version
    - if not exist %LIBRARY_BIN%\sqlite3.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\sqlite3.lib exit 1  # [win]
    - if not exist %LIBRARY_INC%\sqlite3.h exit 1  # [win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.sqlite.org/
  license: Public-Domain (http://www.sqlite.org/copyright.html)
  license_url: http://www.sqlite.org/copyright.html
  summary: 'Implements a self-contained, zero-configuration, SQL database engine.'
  description: |
    SQLite is a self-contained, high-reliability, embedded, full-featured,
    public-domain, SQL database engine.It is the most used database engine
    in the world.
  doc_url: http://www.sqlite.org/docs.html
  doc_source_url: https://github.com/mackyle/sqlite/tree/master/doc
  dev_url: https://github.com/mackyle/sqlite

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - snorfalorpagus
    - mingwandroid
