travis:
  secure:
    BINSTAR_TOKEN: kuHYzrLA40JID87L+9N/eiAP6r5Ambho0MWwuyL+N2TERzpq8mFfPAEC5TNzaVxxfoIFSk4QuqkHckMavfnkAjxBybV4/Hh8f8aWQrqe9Ntj36xpfL9q1d9lXUGA0VGHv5KUh71HBwTCxv/32B1d5qVNLmdzTVNXPADe7n0BB9SC33Bcs+L/thg0nDlFVzq1Bry2CGF7WEDgxUfAFxE/TwfaKseSo1BH8W3daxvBvPLGu4/MtQlYG+4ib6ilEh/AT2YH7EBXiACWt5Dlform9AQxiCmpgMgCXhV3IRzYmHfRRW7iR+/qOd768NQorkyTIr2Q0VTbiWYSFP5GB2mFhOXkfpHpJOFgGJP+uwSDYx29Z5sDRMN4NeHaYorWsrYb5WPQB96BpFgsJzPtz45FqvYbceQ/uhXZaujnElII7uWI5VkahxdLHIm2N6qjPapCgRcCRqaGiqBHVFdxDh8AoCAUkWvq8JV1MO/MCHpyo/ndKsSVl7+7mpYRBRPsD1ERdiZnpg3BfRfgsFXz3VvZMaIU6uY68h0wQux1MsTtd2DXDdL/usE3CDLi2PgyF4NzlAj1B6uE5cTC1ZlknlVkMZgeGTjNb8nPZcv/O31I99VsX6au1mZZqfeyrq7g370IGonMG0dpCgrtFCwmcokKvrTLOK0i4DRgDmklJtEsYEE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
